services:
  neo4j:
    image: neo4j:community
    container_name: neo4j
    restart: unless-stopped
    volumes:
      - neo4j_bkp:/backups
      - neo4j_data:/data
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=${MY_NEO4J_USERNAME}/${MY_NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_client_allow__telemetry=false
      - NEO4J_db_temporal_timezone=Europe/Rome
      - NEO4J_dbms_memory_pagecache_size=4g
      - NEO4J_dbms_usage__report_enabled=false
      - NEO4J_initial_dbms_default__database=${MY_NEO4J_DB_NAME}
      - NEO4J_server_https_enabled=false
      - NEO4J_server_jvm_additional="-XX:+ExitOnOutOfMemoryError"
      - NEO4J_server_logs_debug_enabled=false
      - NEO4J_server_logs_gc_enabled=true
      - NEO4J_server_logs_gc_rotation_keep__number=1
      - NEO4J_server_logs_gc_rotation_size=128m
      - NEO4J_server_memory_heap_max__size=8g
      - NEO4J_server_memory_pagecache_size=4g
    ports:
      - "127.0.0.1:7474:7474" # http
      - "127.0.0.1:7687:7687" # bolt
    deploy:
      resources:
        limits:
          memory: 16G
      restart_policy:
        delay: 5s
        window: 25s
    cpu_count: 4
    platform: linux/amd64
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"
    deploy:
      resources:
        limits:
          memory: 48G
      restart_policy:
        delay: 5s
        window: 25s
    cpu_count: 32
    platform: linux/amd64

volumes:
  neo4j_bkp:
    driver: local
    driver_opts:
      device: ${MY_NEO4J_HOST_BKP_DIR}
      o: "bind,rw"
      type: none
  neo4j_data:
    driver: local
    driver_opts:
      device: ${MY_NEO4J_HOST_DATA_DIR}
      o: "bind,rw"
      type: none
  ollama_data:
    driver: local
    driver_opts:
      device: ${MY_OLLAMA_DATA_DIR}
      o: "bind,rw"
      type: none